### ISSUE TITLE
--debug-port  command line option not working

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction-cli#18]
For both `debug` and `run` option `--debug-port` not working.
While parsing the options  it is resulting into "--debugPort: unknown option."

**Comment by jshimko** [comment]
Already fixed.  Update to v0.5.3.

**Comment by hrath2015** [comment]
OK thanks. Will try after some time. May be not reflecting in npm registry yet. Did an install still showing 5.2.

**Comment by jshimko** [comment]
The site says 0.5.3 already.  There must be some other endpoints that need to update.

https://www.npmjs.com/package/reaction-cli

**Comment by hrath2015** [comment]
Slight time delay.  It is 5.3 now. 👍

**Comment by jshimko** [comment]
Awesome.  Thanks!
