### ISSUE TITLE
adding ssh key generates error if another user named ssh key same filename

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-cli#29]
Receiving this error when adding my ssh key named `launchdock`:

`Error: failed [400] {"id":["SSH Key with this id already exists."]}`

I also tried using `id_rsa.pub`, after Spencer used his `id_rsa.pub`, and received the same error.

When I created an ssh key with a unique name - `gracethedog.pub` - it worked.

Seems like it's not allowing multiple keys with the same name.

**Comment by kieckhafer** [comment]
@jshimko is this ticket relevant anymore? This was discovered the first time we were testing out launchdock.

**Comment by jshimko** [comment]
This is no longer an issue.  Thanks.
