### ISSUE TITLE
meteor 1.5 and reaction-cli not going well together-- windows 10

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction-cli#34]
Keep getting the error on **`reaction `run** 
```sh
=> Started proxy.
=> Started MongoDB.
cfs:gridfs: updating npm dependencies -- mongodb, gridfs-stream...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```
Tried 3-4 times since morning fails consistently.

At the same time` meteor run` works fine without any issue.

**Comment by aaronjudd** [comment]
I saw this a few times as well while trying to use the bundle-visualizer and --production.  I'm not sure this is Windows specific.  Seems like it's been one of those ongoing Meteor issues, that is exacerbated in 1.5.  Each time I got this, I killed all Meteor threads and reran successfully.

**Comment by aaronjudd** [comment]
@jshimko reported this was resolved in https://github.com/reactioncommerce/reaction/issues/2177

The build args he mentions there are setting `TOOL_NODE_FLAGS="--max-old-space-size=2048"` this is also a suggested fix from the various Meteor issues on this topic. You could try that (and maybe we should bake that in??)

**Comment by jshimko** [comment]
Yep, try putting that before the `reaction` command.  You could even go a little higher if your machine has plenty available.  
```sh
TOOL_NODE_FLAGS="--max-old-space-size=4096" reaction
```

**Comment by jshimko** [comment]
Also, for a little more detail...

https://stackoverflow.com/a/42694149/3129944

**Comment by jshimko** [comment]
@hrath2015 is this still an issue for you after updating to Meteor 1.5.1?

**Comment by hrath2015** [comment]
Sorry for delayed response @jshimko 
It is same.  For all fresh install it happens(first time). I close command prompt, open a new one and
`reaction run` to get going.
![image](https://user-images.githubusercontent.com/14071646/28618554-6e8e103e-7222-11e7-9d71-3f282e3a50c9.png)

**Comment by bkilrain** [comment]
I'm getting the exact error when running `reaction build myCustomImage`. Nothing I do can get the image to build... even when running the build on an ec2 box or using docker hub's automated build feature.

**Comment by phenomenon01** [comment]
I also getting this error on my mac , I have tried solutions mention here , but no help.

**Comment by jshimko** [comment]
@bkilrain @phenomenon01 Try doing your docker build with the `TOOL_NODE_FLAGS` arg...

```sh
docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t myCustomImage .
```

**Comment by zenweasel** [comment]
This is resolved by the workaround of adding the TOOL_NODE_FLAGS args. Closing
