### ISSUE TITLE
reaction-cli install on linux installing only for root

### ISSUE THREAD

**Issue by rof20004** [reactioncommerce/reaction-cli#37]
In my O.S Debian Stretch 9 64 bits, when I run;

# npm install -g reaction-cli

this install only for root, not for all users.

I tried too:

# yarn global add reaction-cli

and not working too.

**Comment by jshimko** [comment]
Sounds like you have permissions issues with your global node_modules.  

https://docs.npmjs.com/getting-started/fixing-npm-permissions

This isn't a problem with this package, so I'm going to close this.

**Comment by rof20004** [comment]
Hi, sorry for a little information, in fact, I discovered that when I install reaction-cli, I do not sure, but seems it install inside heroku: /use/local/heroku/bin/reaction

Is this right?

**Comment by jshimko** [comment]
No, that doesn't look right.  I just installed it on a fresh instance of Debian Stretch and it installed in `/usr/lib/node_modules/reaction-cli` and added a symlink for the executable to `/usr/bin/reaction`.

Are you trying to run this on Heroku?  If so, that's not how `reaction-cli` is intended to be used.  It's a tool for local development.  You don't usually run it on remote servers.  

Are you just trying to start up a shop or are you actually writing custom code?

**Comment by rof20004** [comment]
No, my Debian Stretch is an fresh update of Debian Jessie, I just used yarn global add reaction-cli and only worked for root, thanks for answer, I will investigate.

**Comment by jshimko** [comment]
If it only works for root, then [my first answer](https://docs.npmjs.com/getting-started/fixing-npm-permissions) is the solution.  You need to change permissions of the global node_modules directory to be owned by your non-root user.

**Comment by rof20004** [comment]
I will investigate, because all my other npm modules working normal, I have vue-cli, firebase, etc.
