### ISSUE TITLE
reaction run -> halts

### ISSUE THREAD

**Issue by vitaliyterziev** [reactioncommerce/reaction-cli#39]
Followed all in your installation page. All went well but when I run reaction run or reaction the thing just staying there forever..

Windows 7

```sh
$ reaction run

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ ~\E\Bokluci\reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
```

**Comment by jshimko** [comment]
I don't see any errors there.  How long did you wait?  The first build takes at least several minutes depending on your machine.

**Comment by vitaliyterziev** [comment]
~30, 2 core cpu capable of running VS 16 w/o problem

**Comment by jshimko** [comment]
Can you please provide the output of `reaction -v`?

And have you installed all [requirements for Windows](https://docs.reactioncommerce.com/reaction-docs/master/requirements#windows)?

Other than that, I don't know what else to suggest.  Nobody else it reporting this issue.

**Comment by vitaliyterziev** [comment]
this one also took around a minute to print, anyway if no one else reported this issue I guess it can be considered as an edge case, no big deal I was just looking around for a e-comm. platform

Node: 6.11.1
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0

**Comment by vitaliyterziev** [comment]
Hi @zrisher, thank you for your comment. Unfortunately I already gave up on reactioncommerce, when it comes down to making money one need to choose business first solutions, code first are fun to play with but if you have the time.
