### ISSUE TITLE
Time auto CLI message 

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction-cli#42]
Launch CLI Message after 4 weeks from first command ran
TIMED MESSAGE: **Need help with deployment? Learn more about our managed platform: reactioncommerce.com/hosting**

**Comment by jshimko** [comment]
We don't currently record the install time, so I'll have to add that.  I only mention that because this feature won't be able to function retroactively.  The first notifications won't happen until 4 weeks after this update is made.

**Comment by cindyfirestone** [comment]
Updated link for timed message: 
**Need help with deployment? Learn more about the Reaction Platform: http://getrxn.io/reaction-platform**

**Comment by jshimko** [comment]
This is now complete in `v0.21.0`.  Once users update, the 4 week timer starts.  The first command they run _after_ 4 weeks will trigger the message above.
