### ISSUE TITLE
Update Managed Platform Command 

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction-cli#59]
Update the auto response command for any user who types the following: 
`register login whoami keys apps deploy env domains env keys open whoami`

to: 
`This command requires being logged into the Reaction Managed Platform.

If you have an account, please log in and try this command again.
If you don't have an account, please see the link below to learn more.

http://getrxn.io/reaction-platform (Actual URL to be determined upon completion of  [#171](https://github.com/reactioncommerce/reaction-drive/issues/171))

**Comment by aaronjudd** [comment]
@cindyfirestone @jshimko what's the progress?  @cindyfirestone can we discuss that copy, and how that tracking would work, sending to an email?

**Comment by zenweasel** [comment]
@aaronjudd Since @jshimko has been out, if this is urgent should I or somebody else take care of it?

**Comment by jshimko** [comment]
@aaronjudd what's the preference here?  Am I changing this to Cindy's text?  Or something else?

Current text is:

```
This command requires being logged into the managed platform.

If you have an account, please log in and try this command again.
If you you don't have an account, please see the link below to learn more.

http://getrxn.io/reaction-platform
```

**Comment by cindyfirestone** [comment]
@jshimko hold on this, I'll discuss with @aaronjudd tomorrow. Since we're hiding the /hosting page, we need to point them to somewhere else if they run the platform only commands
