### ISSUE TITLE
delete or update reactioncommerce/reaction-cli

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-cli#6]
we should delete or keep this updated 

https://www.npmjs.com/package/@reactioncommerce/reaction-cli

npm's organization stuff is still rather funky I think.

**Comment by jshimko** [comment]
Unpublishing from NPM has apparently [gotten a lot more difficult](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) after the drama a few months ago with that guy essentially unpublishing the internet.  So I marked it as deprecated and added a readme you can't miss.

The readme...
https://www.npmjs.com/package/@reactioncommerce/reaction-cli

The deprecation message when you get if you ignore that and install it anyway...
```sh
$ npm install -g @reactioncommerce/reaction-cli

npm WARN deprecated @reactioncommerce/reaction-cli: This package is deprecated in favor of 'reaction-cli'. Please uninstall this and run 'npm i -g reaction-cli'
```
