### ISSUE TITLE
prompt reaction updates

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-cli#8]
would be good if we could prompt that the reaction version has been updated, similar to what cli is doing for itself, but when the reaction versions are updated.  seems like it could be tricky.. but it would be useful.  maybe branch specific? not sure.

**Comment by jshimko** [comment]
This has been implemented in v0.5.7.  When you run `reaction` to start the app, it gets your current version and compares it to the available tags in Github releases.  If your version is lower, it notifies about the available update and lets you know you can run `reaction pull` to get the latest.  

Of course, this assumes you're on the master branch (which you probably are if your version is old enough to trigger this).  Some branch handling would be the next best thing, but that got complicated pretty quickly.  I think this is probably a reasonable MVP for now.

<img width="465" alt="reaction-update" src="https://cloud.githubusercontent.com/assets/3077956/21779088/15d4bd8e-d674-11e6-8043-9fe9d7fb0057.png">
